# Render deployment configuration for LIA
services:
  - type: web
    name: lia-gov2biz-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free  # Change to 'starter' for production
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard for security
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000  # Render's default port
